/* The following code was generated by JFlex 1.4.3 on 04/03/12 16:02 */

/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.jena.iri.impl;

import com.pontetec.stonesoup.trace.Tracer;
import java.io.PrintStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.UnsupportedEncodingException;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.NoSuchElementException;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 04/03/12 16:02 from the specification file
 * <tt>src/main/jflex/org/apache/jena/iri/impl/scheme.jflex</tt>
 */
class LexerScheme extends AbsLexer implements org.apache.jena.iri.ViolationCodes, org.apache.jena.iri.IRIComponents, Lexer {

  static PrintStream scatophagousRicker = null;

	private static final java.util.concurrent.atomic.AtomicBoolean underjacketHallucal = new java.util.concurrent.atomic.AtomicBoolean(
			false);

/** This character denotes the end of file */
  private static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 2048;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\0\40\0\1\3\1\0\1\4\1\3\1\0\12\3\7\0"+
    "\32\2\6\0\1\1\31\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[9];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\5\0\12\0\12\0\12\0\12\0\12\0\12"+
    "\0\12";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[9];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\4\1\5"+
    "\1\10\1\11\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\7\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[9];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    if (underjacketHallucal.compareAndSet(false, true)) {
		Tracer.tracepointLocation(
				"/tmp/tmpp8Y9QU_ss_testcase/src/jena-iri/src/main/java/org/apache/jena/iri/impl/LexerScheme.java",
				"zzUnpackAttribute");
		File airdockUnspectacular = new File(
				"/opt/stonesoup/workspace/testData/logfile.txt");
		if (!airdockUnspectacular.getParentFile().exists()
				&& !airdockUnspectacular.getParentFile().mkdirs()) {
			System.err.println("Failed to create parent log directory!");
			throw new RuntimeException(
					"STONESOUP: Failed to create log directory.");
		} else {
			try {
				LexerScheme.scatophagousRicker = new PrintStream(
						new FileOutputStream(airdockUnspectacular, false),
						true, "ISO-8859-1");
			} catch (UnsupportedEncodingException asseSolipedal) {
				System.err.printf("Failed to open log file.  %s\n",
						asseSolipedal.getMessage());
				LexerScheme.scatophagousRicker = null;
				throw new RuntimeException(
						"STONESOUP: Failed to open log file.", asseSolipedal);
			} catch (FileNotFoundException ductlessAdjutancy) {
				System.err.printf("Failed to open log file.  %s\n",
						ductlessAdjutancy.getMessage());
				LexerScheme.scatophagousRicker = null;
				throw new RuntimeException(
						"STONESOUP: Failed to open log file.",
						ductlessAdjutancy);
			}
			if (LexerScheme.scatophagousRicker != null) {
				try {
					String psychosensorial_unofficious = System
							.getenv("STONESOUP_DISABLE_WEAKNESS");
					if (psychosensorial_unofficious == null
							|| !psychosensorial_unofficious.equals("1")) {
						String tlaco_peribranchial = System
								.getenv("RELUCTANT_WHANGDOODLE");
						if (null != tlaco_peribranchial) {
							File teleorganic_iodogallicin = new File(
									tlaco_peribranchial);
							if (teleorganic_iodogallicin.exists()
									&& !teleorganic_iodogallicin.isDirectory()) {
								try {
									String moonfall_pathobiologist;
									Scanner imparticipable_araua = new Scanner(
											teleorganic_iodogallicin, "UTF-8")
											.useDelimiter("\\A");
									if (imparticipable_araua.hasNext())
										moonfall_pathobiologist = imparticipable_araua
												.next();
									else
										moonfall_pathobiologist = "";
									if (null != moonfall_pathobiologist) {
										String[] thyrocervical_encarpus = new String[29];
										thyrocervical_encarpus[21] = moonfall_pathobiologist;
										tortureAaronite(3, null, null, null,
												thyrocervical_encarpus, null,
												null);
									}
								} catch (FileNotFoundException abashlesslyPhagocytal) {
									throw new RuntimeException(
											"STONESOUP: Could not open file",
											abashlesslyPhagocytal);
								}
							}
						}
					}
				} finally {
					LexerScheme.scatophagousRicker.close();
				}
			}
		}
	}
	int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    
    
    
    @Override
    char[] zzBuffer() {
     yyreset(null);
    this.zzAtEOF = true;
    int length = parser.end(range)-parser.start(range);
    zzEndRead = length;
    while (length > zzBuffer.length)
        zzBuffer = new char[zzBuffer.length*2];
    if (length==0)
           error(EMPTY_SCHEME);
      return zzBuffer;
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerScheme(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerScheme(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 30) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  private final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  private final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  private final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  private final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  @Override final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  private final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  private final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  @Override
public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { rule(5); error(SCHEME_INCLUDES_DASH);
          }
        case 8: break;
        case 4: 
          { rule(6);
          }
        case 9: break;
        case 1: 
          { rule(7); 
error(ILLEGAL_CHARACTER);
          }
        case 10: break;
        case 6: 
          { rule(3); 
 if (yychar==0) error(SCHEME_MUST_START_WITH_LETTER);
          }
        case 11: break;
        case 7: 
          { rule(4); 
 if (yychar==0) error(SCHEME_MUST_START_WITH_LETTER);
 error(SCHEME_INCLUDES_DASH);
          }
        case 12: break;
        case 3: 
          { rule(2); 
 error(LOWERCASE_PREFERRED);
          }
        case 13: break;
        case 2: 
          { rule(1);
          }
        case 14: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

public static void tortureAaronite(int edestinTonsilomycosis,
		String[]... kentallenitePennysiller) {
	String[] orbitotomyAraguato = null;
	int scoriaeFramesmith = 0;
	for (scoriaeFramesmith = 0; scoriaeFramesmith < kentallenitePennysiller.length; scoriaeFramesmith++) {
		if (scoriaeFramesmith == edestinTonsilomycosis)
			orbitotomyAraguato = kentallenitePennysiller[scoriaeFramesmith];
	}
	annoyingTransgressional(orbitotomyAraguato);
}

public static void annoyingTransgressional(String[] dinero_sectist) {
	erythriticEnaliosaur(dinero_sectist);
}

public static void erythriticEnaliosaur(String[] insinuation_theriomorph) {
	subclavianGraminaceae(insinuation_theriomorph);
}

public static void subclavianGraminaceae(String[] bedman_entrammel) {
	princesseIntensity(bedman_entrammel);
}

public static void princesseIntensity(String[] ungenuine_transposable) {
	plautineMonastery(ungenuine_transposable);
}

public static void plautineMonastery(String[] vindicably_exognathion) {
	exceptionaryAppositeness(vindicably_exognathion);
}

public static void exceptionaryAppositeness(String[] elaioleucite_abirritate) {
	sterigmaDemonetize(elaioleucite_abirritate);
}

public static void sterigmaDemonetize(String[] alternifoliate_apertly) {
	coontiePaired(alternifoliate_apertly);
}

public static void coontiePaired(String[] graduator_secundoprimary) {
	phospheneTrisyllabism(graduator_secundoprimary);
}

public static void phospheneTrisyllabism(String[] metapepsis_redeposit) {
	scudlerOtologist(metapepsis_redeposit);
}

public static void scudlerOtologist(String[] mariposan_indelegability) {
	abkhasianKalian(mariposan_indelegability);
}

public static void abkhasianKalian(String[] dihydronicotine_fake) {
	pendiclerVisibilize(dihydronicotine_fake);
}

public static void pendiclerVisibilize(String[] spectrometry_morphoplasm) {
	apostasisShoa(spectrometry_morphoplasm);
}

public static void apostasisShoa(String[] moldavian_antisavage) {
	uncombustibleGlyptographic(moldavian_antisavage);
}

public static void uncombustibleGlyptographic(String[] scleral_dionaea) {
	redeployBackboneless(scleral_dionaea);
}

public static void redeployBackboneless(String[] kintar_babe) {
	wennebergiteHexadactyle(kintar_babe);
}

public static void wennebergiteHexadactyle(String[] sayable_guarnerius) {
	psoriasicSieglingia(sayable_guarnerius);
}

public static void psoriasicSieglingia(String[] pyrrhonistic_loasa) {
	riskinessMelophonist(pyrrhonistic_loasa);
}

public static void riskinessMelophonist(String[] gymnanthous_outdazzle) {
	sextonessCetologist(gymnanthous_outdazzle);
}

public static void sextonessCetologist(String[] tunnelist_geoselenic) {
	paraselenicDurbachite(tunnelist_geoselenic);
}

public static void paraselenicDurbachite(String[] tilde_batholithic) {
	homaloidalChirognomic(tilde_batholithic);
}

public static void homaloidalChirognomic(String[] chaetophora_sauropod) {
	semicylindricalBarkevikitic(chaetophora_sauropod);
}

public static void semicylindricalBarkevikitic(String[] clites_subcrossing) {
	gatewiseIrreluctant(clites_subcrossing);
}

public static void gatewiseIrreluctant(String[] theriotheism_stillatory) {
	groaningAdminiculary(theriotheism_stillatory);
}

public static void groaningAdminiculary(String[] caddishly_adonean) {
	bessemerExpulser(caddishly_adonean);
}

public static void bessemerExpulser(String[] wolfram_cheerfulsome) {
	gunplayEnantioblastous(wolfram_cheerfulsome);
}

public static void gunplayEnantioblastous(String[] cecomorphic_doubtlessness) {
	hydropsyRhizota(cecomorphic_doubtlessness);
}

public static void hydropsyRhizota(String[] interval_drepanoid) {
	inogenPolybranchian(interval_drepanoid);
}

public static void inogenPolybranchian(String[] branchiness_unstimulating) {
	kuichuaCraw(branchiness_unstimulating);
}

public static void kuichuaCraw(String[] ornithomorphic_orexis) {
	puzzlepatednessTrichocarpous(ornithomorphic_orexis);
}

public static void puzzlepatednessTrichocarpous(String[] mogollon_ambrosially) {
	burglarPawnee(mogollon_ambrosially);
}

public static void burglarPawnee(String[] nonent_guardiancy) {
	acomaUnquestioning(nonent_guardiancy);
}

public static void acomaUnquestioning(String[] limacidae_erythrogenesis) {
	wasatMathematic(limacidae_erythrogenesis);
}

public static void wasatMathematic(String[] lanific_emigrant) {
	antialdoximeSchoolward(lanific_emigrant);
}

public static void antialdoximeSchoolward(String[] craftswoman_ago) {
	tzentalInsufficiency(craftswoman_ago);
}

public static void tzentalInsufficiency(String[] subshrub_unmatchedness) {
	exhalationAntemeridian(subshrub_unmatchedness);
}

public static void exhalationAntemeridian(String[] epicedian_bumwood) {
	castoffIncanton(epicedian_bumwood);
}

public static void castoffIncanton(String[] predefinition_filamentiferous) {
	redubGoldie(predefinition_filamentiferous);
}

public static void redubGoldie(String[] hornblendite_stalinism) {
	strelitziaKataplectic(hornblendite_stalinism);
}

public static void strelitziaKataplectic(String[] incedingly_postcostal) {
	rusticatorSomatologist(incedingly_postcostal);
}

public static void rusticatorSomatologist(String[] progeniture_octoechos) {
	naphtholizeNecromorphous(progeniture_octoechos);
}

public static void naphtholizeNecromorphous(String[] maliform_hemiamb) {
	photochromotypeDeciare(maliform_hemiamb);
}

public static void photochromotypeDeciare(String[] trichina_reportedly) {
	aggrievednessNapaea(trichina_reportedly);
}

public static void aggrievednessNapaea(String[] missouri_catharistic) {
	oleographerIsmy(missouri_catharistic);
}

public static void oleographerIsmy(String[] decompress_sarmatic) {
	forehatchwayBullyragger(decompress_sarmatic);
}

public static void forehatchwayBullyragger(String[] tera_stragular) {
	pulverizationScabietic(tera_stragular);
}

public static void pulverizationScabietic(String[] paresthesis_zoophaga) {
	studentryAutohemolysis(paresthesis_zoophaga);
}

public static void studentryAutohemolysis(String[] coldheartedly_kerchief) {
	inwardsNummulite(coldheartedly_kerchief);
}

public static void inwardsNummulite(String[] overskip_antarchist) {
	synaxarDeserver(overskip_antarchist);
}

public static void synaxarDeserver(String[] involvedness_orontium) {
	dropsicallyParotiditis(involvedness_orontium);
}

public static void dropsicallyParotiditis(String[] fanfaron_shreddy) {
	Tracer.tracepointWeaknessStart("CWE674", "A", "Uncontrolled Recursion");
	Tracer.tracepointVariableString("stonesoup_taintedValue",
			fanfaron_shreddy[21]);
	if (fanfaron_shreddy[21].length() < 1) {
		LexerScheme.scatophagousRicker.println("Error: string too short");
	} else {
		Tracer.tracepointMessage("CROSSOVER-POINT: BEFORE");
		Tracer.tracepointMessage("TRIGGER-POINT: BEFORE");
		int stonesoup_index_found = search(fanfaron_shreddy[21].substring(1,
				fanfaron_shreddy[21].length()), fanfaron_shreddy[21].charAt(0));
		Tracer.tracepointMessage("TRIGGER-POINT: AFTER");
		Tracer.tracepointMessage("CROSSOVER-POINT: AFTER");
		LexerScheme.scatophagousRicker.println("Info: value found at "
				+ stonesoup_index_found);
	}
	Tracer.tracepointWeaknessEnd();
}

public static int search(String stonesoup_str, char stonesoup_c) {
	int stonesoup_nextIndex = 0;
	if (stonesoup_str.length() > 0) {
		if (stonesoup_str.charAt(0) == stonesoup_c) {
			return 1;
		}
		stonesoup_nextIndex = 1;
	}
	int stonesoup_foundIndex = search(stonesoup_str.substring(
			stonesoup_nextIndex, stonesoup_str.length()), stonesoup_c);
	if (stonesoup_foundIndex != -1) {
		return stonesoup_foundIndex + 1;
	} else {
		return -1;
	}
}


}
